cni: multus,canal
cluster-cidr: 10.42.0.0/16
service-cidr: 10.42.0.0/16
kubelet-arg:
- --allowed-unsafe-sysctls=net.*
# - --feature-gates=CPUManager=true
# --topology-manager-policy=best-effort
# - --cpu-manager-policy=static
pause-image: k8s.gcr.io/pause:3.3
kube-proxy-arg:
- --metrics-bind-address=0.0.0.0:10249
- --proxy-mode=ipvs
kube-apiserver-arg:
- --service-node-port-range=2000-36767
node-label:
- "node-role.aetherproject.org=omec-upf"
